Feature/anemometer roles
pdffillerdocker/anemometer-backend pull request #13
Opened 2022-10-25 17:07 UTC by moonchildua

add accountIDs parsing from org account.
collect slowlogs from accounts with assumed role
fix file format for mysql engine.

2022-11-01 15:20 UTC, Sarga approved these changes

2022-11-02 07:33 UTC, daimon243 requested changes

2022-11-02 07:33 UTC, daimon243 commented on entrypoint.sh
> +  --role-session-name ${rolesessionName} \
--external-id ${external-id} ???

2022-11-04 04:30 UTC, daimon243 approved these changes

2022-11-07 10:45 UTC, moonchildua commented on entrypoint.sh
> +  --role-session-name ${rolesessionName} \
add

2022-11-09 10:27 UTC, merged